### ISSUE TITLE
Bidirectional communication

### ISSUE THREAD

**Issue by kr0ner** [theosnel/python-xsense#4]
Hi there @theosnel. Thanks for this great project. Been looking forward to this since ages.

Do you plan to add bidirectional communication at some point? Is it even possible?
Would be nice to be able to schedule e.g. automated testing for smoke detectors.

**Comment by theosnel** [comment]
Hi, @kr0ner, the last release includes 2-way-communication, but it is still very limited. It is hard to figure out the exact message each device needs. For now it is only included in the async client.
Everything is still under heavy development, so things will change over time.

**Comment by kr0ner** [comment]
Thanks a lot for your time and effort. Bidirectional communication would be just a nice to have. The current functionality is all I need right now 🫡

**Comment by kr0ner** [comment]
Seems to work. Closing this. Thanks 👍🏼
