### ISSUE TITLE
Support of SBS10 and and XS03-iWX

### ISSUE THREAD

**Issue by kimzeuner** [theosnel/python-xsense#5]
Hi and first of all thanks for your project. I have been waiting for something like this!
Unfortunately it seems as my setup is not supported yet. Do you have any ideas how i can make it work or how i can support making it work ? 
As mentioned in the title i have an SBS10 and 6 smoke sensors XS03-iWX that are connected to the SBS10. I have shared them to a second account which i am using in Home Assistant. 
I get the following error which makes me think that my devices are not supported yet:
![xsense_failure](https://github.com/user-attachments/assets/4121b10d-6d7a-475f-a11a-1ddd7c5e79c1)
Maybe i can share my devices with you so you can check the API calls or explain me how to do it on my own ? 

Thanks in advance!

**Comment by Mike091961** [comment]
Hello , I would be happy if this will be implemented because I use the same devices.
Thanks al lot

**Comment by theosnel** [comment]
I need to reverse engineer the api-calls for each device, so without access to one of those it is impossible for me. Would it be possible to invite me to your devices? You can use xsensedev@theo.snelleman.net.

**Comment by kimzeuner** [comment]
Sure, i just shared my devices with the mentioned account.

**Comment by theosnel** [comment]
Thanks, I was able to check the urls to fetch the info. They where slightly different for the SBS10.

Just released an update (0.0.12) that uses the other urls for the SBS10. Hopefully nothing else is different, but I so far I didn't find any issues. Let me know if you find anything else.
It is helpful for me to see all the different products with their slightly different API's. The code isn't too pretty, but it will do the job. When we know all variaties I could do a rewrite one day to clean it up.

I've asked Jarnsen to update the HACS package.

**Comment by kimzeuner** [comment]
Wow that sounds great, i will test as soon as the new version is available and let you know if it works.

**Comment by kimzeuner** [comment]
I have just checked the new version and everything seems to work fine. 
This is one of my devices, are there all entities that you would expect ? 

![image](https://github.com/user-attachments/assets/8e70769f-d8a3-4678-af07-2b30d1495609)

Thanks again!

**Comment by Mike091961** [comment]
I'm thrilled, it works fine :-)
Thanks a lot
One Device:
![image](https://github.com/user-attachments/assets/43fa21d1-da3f-479e-8a5a-df9273c23152)
And the Basisstation:
![image](https://github.com/user-attachments/assets/7e29d279-15a6-44fc-8328-cdea24a714bd)
