### ISSUE TITLE
Question with regards to the cognito handling

### ISSUE THREAD

**Issue by basraayman** [theosnel/python-xsense#9]
Hi Theo,

thanks a lot for your effort and work. I've been trying to get something similar set up for Homey, and am in the process of coding that up. Based on your work I was able to log into the x-sense API, and I get the info back (secret, id, etc). The part that stumps me at the moment is that when I then post a request to cognito, I always get this response back:

```
{
    "__type": "NotAuthorizedException",
    "message": "SecretHash does not match for the client: <client id>"
}
```

I use a small script to create the secret hash:
```
import base64
import hmac
import hashlib

def secret_hash(username, client_id, client_secret):
    """
    Calculate the secret hash required by Cognito when the client is configured with a secret.

    Args:
        username (str): The username of the Cognito user.
        client_id (str): The Cognito app client ID.
        client_secret (str): The Cognito app client secret.

    Returns:
        str: The calculated secret hash as a base64-encoded string.
    """
    message = f"{username}{client_id}".encode('utf-8')
    key = client_secret.encode('utf-8')
    dig = hmac.new(key, message, hashlib.sha256).digest()
    secret_hash_value = base64.b64encode(dig).decode('utf-8')
    return secret_hash_value

username = "<email>"
client_id = "<client_id>"
client_secret = "<client_secret>"

# Compute the secret hash
secret_hash_value = secret_hash(username, client_id, client_secret)
print(f"Calculated SECRET_HASH: {secret_hash_value}")
```

And then submit the body like so to the region :
```
{
    "AuthFlow": "USER_PASSWORD_AUTH",
    "ClientId": "<client-id>",
    "AuthParameters": {
        "USERNAME": "<email-address>",
        "PASSWORD": "<password>",
        "SECRET_HASH": "<the calculated hash>"
    }
}
```

But somehow the hash does not seem to match. Would you happen to have any idea where this might be going wrong? I'll make sure to credit you for your work either way since it forms a basis for what I'm doing, so thanks again either way! :)

**Comment by theosnel** [comment]
Hi Bas,
The authentication in my code is something that needs work. I now use several external libraries and everything is sync. So I don't know all details yet, I just got it working.

Maybe it has something to do with the AuthFlow. I think I use 'USER_SRP_AUTH' and not 'USER_PASSWORD_AUTH'.

**Comment by basraayman** [comment]
Thanks for your response, Theo. It seems that I get a clientSecret back that is 77 characters long. I think the error I am having is related with the conversion of my clientSecret to the secret_hash that cognito wants. Afaik, Cognito wants a 32 byte long key. The issue is when I decode my clientSecret in base64 it does not meet the length requirement. I also can't use it as is, so I'm trying to figure what I need to do to convert it so I can generate my secret_hash. If you have any tips on what you encountered or did to get this to work, I think that might already be the missing piece to get me unblocked. :)

**Comment by theosnel** [comment]
When you retrieve the client-id and secret from x-sense, you'll get a base64 encoded secret key.
I don't know why, but after decoding it, you have to slice it and remove the first 4 bytes (looks like a version number) and the last byte. ( [4:-1])
My secret starts with 'folnk' and ends with '3v1' (Although it is kinda public, it still feels wrong to post it online)
The client-id and secret for android is different than for ios, so you might have a different key.

Besides the secret, I cannot spot any differences.

**Comment by basraayman** [comment]
That did the trick, I can now get the access, ID and Refresh tokens. Appreciate the pointer in the right direction! Happy holidays. ☺️

**Comment by theosnel** [comment]
Cool! Feel free to ask if you have any further issues. And please keep me in the loop if you have nice developments.

Do you want to use mqtt for the realtime updates?
Fyi: currently working on the xsense alarm system and have some progress on adding support for camera's. 

Happy holidays too!
